- hosts: all
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Copy index.html 
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true
